// Catalog seed data. Kept free of Prisma imports so tooling (e.g. the product
// image fetcher) can read it without a generated client.

const categories = [
  { id: "veg", name: "Vegetables", emoji: "🥬", description: "Farm-picked greens and staples." },
  { id: "fruit", name: "Fruits", emoji: "🍊", description: "Vitamin-rich seasonal fruits." },
  { id: "dairy", name: "Dairy", emoji: "🥛", description: "Milk, paneer, yogurt, and butter." },
  { id: "snacks", name: "Snacks", emoji: "🥨", description: "Evening bites and pantry treats." },
  { id: "beverages", name: "Beverages", emoji: "🥤", description: "Cold, fresh, and energizing drinks." },
  { id: "essentials", name: "Essentials", emoji: "🧼", description: "Home-care and everyday basics." },
  { id: "bakery", name: "Bakery", emoji: "🍞", description: "Fresh breads, pastries, and baked goods." },
  { id: "vegan", name: "Vegan", emoji: "🌱", description: "Plant-based and cruelty-free options." },
  { id: "meat", name: "Meat", emoji: "🥩", description: "Fresh meats and protein sources." },
];

const products = [
  {
    id: "prod-avocado",
    slug: "hass-avocado-pack",
    name: "Hass Avocado Pack",
    brand: "GreenHarvest",
    categoryId: "fruit",
    price: 169,
    compareAtPrice: 199,
    rating: 4.8,
    stock: 42,
    eta: "10 mins",
    unit: "2 pcs",
    tags: ["Fresh", "Premium", "Breakfast"],
    description: "Buttery avocados sourced for toast, bowls, and smoothies.",
  },
  {
    id: "prod-spinach",
    slug: "baby-spinach-bag",
    name: "Baby Spinach Bag",
    brand: "Leaf District",
    categoryId: "veg",
    price: 79,
    compareAtPrice: 95,
    rating: 4.6,
    stock: 58,
    eta: "8 mins",
    unit: "250 g",
    tags: ["Leafy", "Salads", "Iron-rich"],
    description: "Tender spinach leaves washed and packed for quick meals.",
  },
  {
    id: "prod-milk",
    slug: "organic-toned-milk",
    name: "Organic Toned Milk",
    brand: "Morning Meadow",
    categoryId: "dairy",
    price: 62,
    rating: 4.7,
    stock: 100,
    eta: "9 mins",
    unit: "1 ltr",
    tags: ["Protein", "Daily", "Organic"],
    description: "Daily-use toned milk from certified farms with cold-chain handling.",
  },
  {
    id: "prod-paneer",
    slug: "fresh-malai-paneer",
    name: "Fresh Malai Paneer",
    brand: "Dairy Craft",
    categoryId: "dairy",
    price: 115,
    compareAtPrice: 129,
    rating: 4.9,
    stock: 36,
    eta: "12 mins",
    unit: "200 g",
    tags: ["High protein", "Fresh", "Dinner"],
    description: "Soft paneer cubes crafted for curries, wraps, and grilled meals.",
  },
  {
    id: "prod-granola",
    slug: "berry-almond-granola",
    name: "Berry Almond Granola",
    brand: "Mornings Co.",
    categoryId: "snacks",
    price: 289,
    rating: 4.5,
    stock: 26,
    eta: "14 mins",
    unit: "400 g",
    tags: ["Healthy", "Breakfast", "Crunchy"],
    description: "Small-batch granola loaded with dried berries and roasted almonds.",
  },
  {
    id: "prod-coldbrew",
    slug: "classic-cold-brew",
    name: "Classic Cold Brew",
    brand: "Roast Lane",
    categoryId: "beverages",
    price: 149,
    rating: 4.4,
    stock: 54,
    eta: "11 mins",
    unit: "300 ml",
    tags: ["Coffee", "Chilled", "Ready to drink"],
    description: "Slow-steeped cold brew with cocoa notes and a smooth finish.",
  },
  {
    id: "prod-oranges",
    slug: "nagpur-oranges-box",
    name: "Nagpur Oranges Box",
    brand: "Citrus Route",
    categoryId: "fruit",
    price: 199,
    compareAtPrice: 239,
    rating: 4.8,
    stock: 62,
    eta: "7 mins",
    unit: "1 kg",
    tags: ["Juicy", "Vitamin C", "Seasonal"],
    description: "Sweet, easy-peel oranges packed for family breakfasts and juicing.",
  },
  {
    id: "prod-detergent",
    slug: "plant-safe-detergent",
    name: "Plant Safe Detergent",
    brand: "HomeKind",
    categoryId: "essentials",
    price: 349,
    rating: 4.3,
    stock: 18,
    eta: "16 mins",
    unit: "2 ltr",
    tags: ["Home care", "Eco", "Refill"],
    description: "Low-residue liquid detergent with a soft botanical fragrance.",
  },
  // Products from GitHub supermarket example
  {
    id: "prod-brown-eggs",
    slug: "brown-eggs",
    name: "Brown Eggs",
    brand: "FarmFresh",
    categoryId: "dairy",
    price: 281,
    rating: 4.0,
    stock: 50,
    eta: "10 mins",
    unit: "12 pcs",
    tags: ["Protein", "Organic", "Breakfast"],
    description: "Raw organic brown eggs in a basket",
  },
  {
    id: "prod-strawberry",
    slug: "sweet-fresh-strawberry",
    name: "Sweet Fresh Strawberry",
    brand: "BerryFarm",
    categoryId: "fruit",
    price: 295,
    rating: 4.0,
    stock: 35,
    eta: "12 mins",
    unit: "500 g",
    tags: ["Sweet", "Fresh", "Seasonal"],
    description: "Sweet fresh strawberry on the wooden table",
  },
  {
    id: "prod-asparagus",
    slug: "asparagus",
    name: "Asparagus",
    brand: "GreenValley",
    categoryId: "veg",
    price: 190,
    rating: 3.0,
    stock: 25,
    eta: "15 mins",
    unit: "400 g",
    tags: ["Fresh", "Healthy", "Vegetable"],
    description: "Asparagus with ham on the wooden table",
  },
  {
    id: "prod-green-smoothie",
    slug: "green-smoothie",
    name: "Green Smoothie",
    brand: "SmoothieCo",
    categoryId: "dairy",
    price: 177,
    rating: 4.0,
    stock: 30,
    eta: "8 mins",
    unit: "350 ml",
    tags: ["Healthy", "Drink", "Fresh"],
    description: "Glass of green smoothie with quail egg's yolk, served with cocktail tube, green apple and baby spinach leaves over tin surface",
  },
  {
    id: "prod-raw-legums",
    slug: "raw-legums",
    name: "Raw Legums",
    brand: "OrganicFarms",
    categoryId: "veg",
    price: 171,
    rating: 2.0,
    stock: 40,
    eta: "14 mins",
    unit: "500 g",
    tags: ["Organic", "Protein", "Legumes"],
    description: "Raw legums on the wooden table",
  },
  {
    id: "prod-baking-cake",
    slug: "baking-cake",
    name: "Baking Cake",
    brand: "SweetBakery",
    categoryId: "bakery",
    price: 111,
    rating: 4.0,
    stock: 20,
    eta: "18 mins",
    unit: "1 kg",
    tags: ["Sweet", "Dessert", "Bakery"],
    description: "Baking cake in rural kitchen - dough recipe ingredients (eggs, flour, sugar) on vintage wooden table from above",
  },
  {
    id: "prod-pesto",
    slug: "pesto-with-basil",
    name: "Pesto with Basil",
    brand: "ItalianKitchen",
    categoryId: "veg",
    price: 182,
    rating: 2.0,
    stock: 28,
    eta: "16 mins",
    unit: "200 g",
    tags: ["Italian", "Sauce", "Fresh"],
    description: "Italian traditional pesto with basil, cheese and oil",
  },
  {
    id: "prod-hazelnut",
    slug: "hazelnut-bowl",
    name: "Hazelnut in Black Ceramic Bowl",
    brand: "NutHarvest",
    categoryId: "veg",
    price: 274,
    rating: 0.0,
    stock: 22,
    eta: "20 mins",
    unit: "300 g",
    tags: ["Nuts", "Healthy", "Snack"],
    description: "Hazelnut in black ceramic bowl on old wooden background. forest wealth. rustic style. selective focus",
  },
  {
    id: "prod-fresh-strawberry-2",
    slug: "fresh-strawberry",
    name: "Fresh Strawberry",
    brand: "BerryFarm",
    categoryId: "fruit",
    price: 286,
    rating: 4.0,
    stock: 45,
    eta: "11 mins",
    unit: "500 g",
    tags: ["Fresh", "Sweet", "Seasonal"],
    description: "Sweet fresh strawberry on the wooden table",
  },
  {
    id: "prod-lemon-salt",
    slug: "lemon-and-salt",
    name: "Lemon and Salt",
    brand: "CitrusGrove",
    categoryId: "fruit",
    price: 158,
    rating: 5.0,
    stock: 38,
    eta: "13 mins",
    unit: "500 g",
    tags: ["Citrus", "Fresh", "Seasoning"],
    description: "Rosemary, lemon and salt on the table",
  },
  {
    id: "prod-homemade-bread",
    slug: "homemade-bread",
    name: "Homemade Bread",
    brand: "ArtisanBakery",
    categoryId: "bakery",
    price: 175,
    rating: 3.0,
    stock: 15,
    eta: "25 mins",
    unit: "500 g",
    tags: ["Fresh", "Bakery", "Artisan"],
    description: "Homemade bread",
  },
  {
    id: "prod-legums-cooked",
    slug: "cooked-legums",
    name: "Cooked Legums",
    brand: "OrganicFarms",
    categoryId: "veg",
    price: 148,
    rating: 0.0,
    stock: 32,
    eta: "12 mins",
    unit: "400 g",
    tags: ["Cooked", "Protein", "Ready"],
    description: "Cooked legums on the wooden table",
  },
  {
    id: "prod-fresh-tomato",
    slug: "fresh-tomato",
    name: "Fresh Tomato",
    brand: "TomatoFarm",
    categoryId: "veg",
    price: 163,
    rating: 2.0,
    stock: 55,
    eta: "10 mins",
    unit: "500 g",
    tags: ["Fresh", "Vegetable", "Salad"],
    description: "Fresh tomato juice with basil",
  },
  {
    id: "prod-healthy-breakfast",
    slug: "healthy-breakfast",
    name: "Healthy Breakfast",
    brand: "MorningBowl",
    categoryId: "fruit",
    price: 130,
    rating: 2.0,
    stock: 28,
    eta: "15 mins",
    unit: "400 g",
    tags: ["Healthy", "Breakfast", "Berries"],
    description: "Healthy breakfast set. rice cereal or porridge with berries and honey over rustic wood background",
  },
  {
    id: "prod-green-beans",
    slug: "green-beans",
    name: "Green Beans",
    brand: "GreenHarvest",
    categoryId: "veg",
    price: 288,
    rating: 1.0,
    stock: 42,
    eta: "14 mins",
    unit: "400 g",
    tags: ["Fresh", "Vegetable", "Organic"],
    description: "Raw organic green beans ready to eat",
  },
  {
    id: "prod-portabello",
    slug: "baked-stuffed-portabello",
    name: "Baked Stuffed Portabello Mushrooms",
    brand: "MushroomFarm",
    categoryId: "bakery",
    price: 203,
    rating: 1.0,
    stock: 18,
    eta: "22 mins",
    unit: "300 g",
    tags: ["Baked", "Mushroom", "Vegetarian"],
    description: "Homemade baked stuffed portabello mushrooms with spinach and cheese",
  },
  {
    id: "prod-strawberry-jelly",
    slug: "strawberry-jelly",
    name: "Strawberry Jelly",
    brand: "BerryPreserves",
    categoryId: "fruit",
    price: 142,
    rating: 1.0,
    stock: 24,
    eta: "18 mins",
    unit: "300 g",
    tags: ["Sweet", "Spread", "Organic"],
    description: "Homemade organic strawberry jelly in a jar",
  },
  {
    id: "prod-pears-juice",
    slug: "pears-juice",
    name: "Pears Juice",
    brand: "FreshPress",
    categoryId: "fruit",
    price: 195,
    rating: 4.0,
    stock: 35,
    eta: "9 mins",
    unit: "1 ltr",
    tags: ["Fresh", "Juice", "Fruit"],
    description: "Fresh pears juice on the wooden table",
  },
  {
    id: "prod-fresh-pears",
    slug: "fresh-pears",
    name: "Fresh Pears",
    brand: "OrchardFresh",
    categoryId: "fruit",
    price: 151,
    rating: 5.0,
    stock: 48,
    eta: "12 mins",
    unit: "1 kg",
    tags: ["Fresh", "Sweet", "Seasonal"],
    description: "Sweet fresh pears on the wooden table",
  },
  {
    id: "prod-caprese-salad",
    slug: "caprese-salad",
    name: "Caprese Salad",
    brand: "ItalianKitchen",
    categoryId: "veg",
    price: 168,
    rating: 5.0,
    stock: 22,
    eta: "16 mins",
    unit: "350 g",
    tags: ["Fresh", "Salad", "Italian"],
    description: "Homemade healthy caprese salad with tomato mozzarella and basil",
  },
  {
    id: "prod-orange-popsicle",
    slug: "oranges",
    name: "Oranges",
    brand: "CitrusGrove",
    categoryId: "fruit",
    price: 215,
    rating: 4.0,
    stock: 60,
    eta: "11 mins",
    unit: "1 kg",
    tags: ["Citrus", "Fresh", "Vitamin C"],
    description: "Orange popsicle ice cream bars made from fresh oranges. a refreshing summer treat",
  },
  {
    id: "prod-vegan-food",
    slug: "vegan-food",
    name: "Vegan Food",
    brand: "PlantBased",
    categoryId: "vegan",
    price: 297,
    rating: 4.0,
    stock: 25,
    eta: "18 mins",
    unit: "400 g",
    tags: ["Vegan", "Plant-based", "Healthy"],
    description: "Concept of vegan food",
  },
  {
    id: "prod-breakfast-muesli",
    slug: "breakfast-with-muesli",
    name: "Breakfast with Muesli",
    brand: "MorningBowl",
    categoryId: "dairy",
    price: 227,
    rating: 2.0,
    stock: 32,
    eta: "14 mins",
    unit: "400 g",
    tags: ["Healthy", "Breakfast", "Grains"],
    description: "Concept of healthy breakfast with muesli",
  },
  {
    id: "prod-honey",
    slug: "honey",
    name: "Honey",
    brand: "BeeHive",
    categoryId: "bakery",
    price: 170,
    rating: 2.0,
    stock: 20,
    eta: "20 mins",
    unit: "300 g",
    tags: ["Natural", "Sweet", "Organic"],
    description: "Honey and honeycell on the table",
  },
  {
    id: "prod-breakfast-cottage",
    slug: "breakfast-with-cottage",
    name: "Breakfast with Cottage",
    brand: "DairyFresh",
    categoryId: "fruit",
    price: 141,
    rating: 1.0,
    stock: 28,
    eta: "12 mins",
    unit: "350 g",
    tags: ["Healthy", "Breakfast", "Dairy"],
    description: "Healthy breakfast with cottage cheese and strawberry",
  },
  {
    id: "prod-strawberry-smoothie",
    slug: "strawberry-smoothie",
    name: "Strawberry Smoothie",
    brand: "SmoothieCo",
    categoryId: "fruit",
    price: 289,
    rating: 2.0,
    stock: 30,
    eta: "8 mins",
    unit: "400 ml",
    tags: ["Fresh", "Drink", "Berry"],
    description: "Glass of red strawberry smoothie with chia seeds, served with retro cocktail tube, fresh mint and strawberries over dark background",
  },
  {
    id: "prod-strawberry-mint",
    slug: "strawberry-and-mint",
    name: "Strawberry and Mint",
    brand: "MorningBowl",
    categoryId: "fruit",
    price: 262,
    rating: 4.0,
    stock: 26,
    eta: "15 mins",
    unit: "350 g",
    tags: ["Fresh", "Muesli", "Berry"],
    description: "Homemade muesli with strawberry and mint",
  },
  {
    id: "prod-ricotta",
    slug: "ricotta",
    name: "Ricotta",
    brand: "DairyCraft",
    categoryId: "dairy",
    price: 278,
    rating: 5.0,
    stock: 22,
    eta: "13 mins",
    unit: "300 g",
    tags: ["Fresh", "Cheese", "Italian"],
    description: "Ricotta with berry and mint",
  },
  {
    id: "prod-cuban-sandwich",
    slug: "cuban-sandwich",
    name: "Cuban Sandwich",
    brand: "SandwichShop",
    categoryId: "bakery",
    price: 185,
    rating: 4.0,
    stock: 18,
    eta: "20 mins",
    unit: "1 pc",
    tags: ["Sandwich", "Bakery", "Lunch"],
    description: "Homemade traditional cuban sandwiches with ham pork and cheese",
  },
  {
    id: "prod-granola-jar",
    slug: "granola",
    name: "Granola",
    brand: "MorningBowl",
    categoryId: "dairy",
    price: 300,
    rating: 3.0,
    stock: 24,
    eta: "16 mins",
    unit: "450 g",
    tags: ["Healthy", "Breakfast", "Nuts"],
    description: "Glass jar with homemade granola and yogurt with nuts, raspberries and blackberries on wooden cutting board over white textile in day light",
  },
  {
    id: "prod-smoothie-chia",
    slug: "smoothie-with-chia-seeds",
    name: "Smoothie with Chia Seeds",
    brand: "SmoothieCo",
    categoryId: "fruit",
    price: 253,
    rating: 5.0,
    stock: 32,
    eta: "8 mins",
    unit: "400 ml",
    tags: ["Healthy", "Drink", "Chia"],
    description: "Glass of red strawberry smoothie with chia seeds, served with retro cocktail tube, fresh mint and strawberries over wooden table",
  },
  {
    id: "prod-yogurt",
    slug: "yogurt",
    name: "Yogurt",
    brand: "DairyFresh",
    categoryId: "dairy",
    price: 276,
    rating: 4.0,
    stock: 35,
    eta: "10 mins",
    unit: "400 g",
    tags: ["Fresh", "Probiotic", "Healthy"],
    description: "Homemade yogurt with raspberry and mint",
  },
  {
    id: "prod-sandwich-salad",
    slug: "sandwich-with-salad",
    name: "Sandwich with Salad",
    brand: "VeganBites",
    categoryId: "veg",
    price: 225,
    rating: 5.0,
    stock: 20,
    eta: "18 mins",
    unit: "1 pc",
    tags: ["Vegan", "Sandwich", "Fresh"],
    description: "Vegan sandwich with salad, tomato and radish",
  },
  {
    id: "prod-cherry",
    slug: "cherry",
    name: "Cherry",
    brand: "OrchardFresh",
    categoryId: "fruit",
    price: 144,
    rating: 5.0,
    stock: 38,
    eta: "14 mins",
    unit: "400 g",
    tags: ["Fresh", "Sweet", "Seasonal"],
    description: "Cherry with sugar on old table",
  },
  {
    id: "prod-raw-asparagus",
    slug: "raw-asparagus",
    name: "Raw Asparagus",
    brand: "GreenHarvest",
    categoryId: "veg",
    price: 230,
    rating: 4.0,
    stock: 30,
    eta: "16 mins",
    unit: "400 g",
    tags: ["Fresh", "Vegetable", "Salad"],
    description: "Raw fresh asparagus salad with cheese and dressing",
  },
  {
    id: "prod-corn",
    slug: "corn",
    name: "Corn",
    brand: "FarmFresh",
    categoryId: "veg",
    price: 136,
    rating: 2.0,
    stock: 45,
    eta: "15 mins",
    unit: "2 pcs",
    tags: ["Fresh", "Vegetable", "Grilled"],
    description: "Grilled corn on the cob with salt and butter",
  },
  {
    id: "prod-vegan-healthy",
    slug: "vegan-healthy",
    name: "Vegan Healthy",
    brand: "PlantBased",
    categoryId: "vegan",
    price: 290,
    rating: 5.0,
    stock: 22,
    eta: "20 mins",
    unit: "400 g",
    tags: ["Vegan", "Healthy", "Plant-based"],
    description: "Concept of healthy vegan eating",
  },
  {
    id: "prod-blueberries",
    slug: "fresh-blueberries",
    name: "Fresh Blueberries",
    brand: "BerryFarm",
    categoryId: "fruit",
    price: 210,
    rating: 4.0,
    stock: 40,
    eta: "12 mins",
    unit: "300 g",
    tags: ["Fresh", "Berry", "Antioxidant"],
    description: "Healthy breakfast. berry crumble with fresh blueberries, raspberries, strawberries, almond, walnuts, pecans, yogurt, and mint in ceramic plates over white wooden surface, top view",
  },
  {
    id: "prod-smashed-avocado",
    slug: "smashed-avocado",
    name: "Smashed Avocado",
    brand: "VeganBites",
    categoryId: "fruit",
    price: 259,
    rating: 0.0,
    stock: 28,
    eta: "15 mins",
    unit: "350 g",
    tags: ["Vegan", "Avocado", "Fresh"],
    description: "Vegan sandwiches with smashed avocado, tomatoes and radish. top view",
  },
  {
    id: "prod-ciabatta",
    slug: "italian-ciabatta",
    name: "Italian Ciabatta",
    brand: "ArtisanBakery",
    categoryId: "bakery",
    price: 152,
    rating: 1.0,
    stock: 16,
    eta: "25 mins",
    unit: "400 g",
    tags: ["Italian", "Bread", "Artisan"],
    description: "Italian ciabatta bread cut in slices on wooden chopping board with herbs, garlic and olives over dark grunge backdrop, top view",
  },
  {
    id: "prod-rustic-breakfast",
    slug: "rustic-breakfast",
    name: "Rustic Breakfast",
    brand: "MorningBowl",
    categoryId: "dairy",
    price: 213,
    rating: 0.0,
    stock: 24,
    eta: "18 mins",
    unit: "400 g",
    tags: ["Healthy", "Breakfast", "Grains"],
    description: "Rustic healthy breakfast set. cooked buckwheat groats with milk and honey on dark grunge backdrop. top view, copy space",
  },
  {
    id: "prod-sliced-lemons",
    slug: "sliced-lemons",
    name: "Sliced Lemons",
    brand: "CitrusGrove",
    categoryId: "fruit",
    price: 271,
    rating: 2.0,
    stock: 35,
    eta: "13 mins",
    unit: "1 kg",
    tags: ["Citrus", "Fresh", "Seasoning"],
    description: "Heap of whole and sliced lemons and limes with mint in vintage metal grid box over old wooden table with turquoise wooden background. dark rustic style",
  },
  {
    id: "prod-plums",
    slug: "plums",
    name: "Plums",
    brand: "OrchardFresh",
    categoryId: "fruit",
    price: 192,
    rating: 1.0,
    stock: 32,
    eta: "14 mins",
    unit: "500 g",
    tags: ["Fresh", "Sweet", "Seasonal"],
    description: "Yellow and red sweet plums",
  },
  {
    id: "prod-french-fries",
    slug: "french-fries",
    name: "French Fries",
    brand: "FastBites",
    categoryId: "bakery",
    price: 183,
    rating: 3.0,
    stock: 25,
    eta: "22 mins",
    unit: "300 g",
    tags: ["Snack", "Baked", "Potato"],
    description: "Homemade oven baked french fries with ketchup",
  },
  {
    id: "prod-strawberries-2",
    slug: "strawberries",
    name: "Strawberries",
    brand: "BerryFarm",
    categoryId: "fruit",
    price: 151,
    rating: 3.0,
    stock: 42,
    eta: "11 mins",
    unit: "400 g",
    tags: ["Fresh", "Sweet", "Berry"],
    description: "Healthy breakfast set. rice cereal or porridge with fresh strawberry, apricots, almond and honey over white rustic wood backdrop, top view",
  },
  {
    id: "prod-ground-beef",
    slug: "ground-beef-meat-burger",
    name: "Ground Beef Meat Burger",
    brand: "MeatMaster",
    categoryId: "meat",
    price: 117,
    rating: 5.0,
    stock: 20,
    eta: "25 mins",
    unit: "500 g",
    tags: ["Meat", "Protein", "Fresh"],
    description: "Raw ground beef meat burger steak cutlets with seasoning on vintage wooden boards, black background",
  },
  {
    id: "prod-tomatoes",
    slug: "tomatoes",
    name: "Tomatoes",
    brand: "TomatoFarm",
    categoryId: "fruit",
    price: 260,
    rating: 4.0,
    stock: 55,
    eta: "10 mins",
    unit: "1 kg",
    tags: ["Fresh", "Organic", "Vegetable"],
    description: "Organic tomatoes made with love",
  },
  {
    id: "prod-basil",
    slug: "basil",
    name: "Basil",
    brand: "HerbGarden",
    categoryId: "veg",
    price: 152,
    rating: 4.0,
    stock: 30,
    eta: "12 mins",
    unit: "100 g",
    tags: ["Fresh", "Herb", "Organic"],
    description: "Concept of vegan food with basil",
  },
  {
    id: "prod-fruits-bouquet",
    slug: "fruits-bouquet",
    name: "Fruits Bouquet",
    brand: "CitrusGrove",
    categoryId: "fruit",
    price: 182,
    rating: 1.0,
    stock: 15,
    eta: "18 mins",
    unit: "1 pc",
    tags: ["Fresh", "Citrus", "Gift"],
    description: "Abstract citrus fruits bouquet on blue background",
  },
  {
    id: "prod-peaches",
    slug: "peaches-on-branch",
    name: "Peaches on Branch",
    brand: "OrchardFresh",
    categoryId: "fruit",
    price: 256,
    rating: 3.0,
    stock: 28,
    eta: "16 mins",
    unit: "1 kg",
    tags: ["Fresh", "Sweet", "Seasonal"],
    description: "Peaches on branch with leaves and glasses with peach juice and limonade with ice cubes in aluminum tray over old metal table. dark rustic style. top view",
  },
];

module.exports = { categories, products };
