// Catalog seed data. Kept free of Prisma imports so tooling (e.g. the product
// image fetcher) can read it without a generated client.

const categories = [
  { id: "veg", name: "Vegetables", emoji: "🥬", description: "Farm-picked greens and staples." },
  { id: "fruit", name: "Fruits", emoji: "🍊", description: "Vitamin-rich seasonal fruits." },
  { id: "dairy", name: "Dairy", emoji: "🥛", description: "Milk, paneer, yogurt, and butter." },
  { id: "snacks", name: "Snacks", emoji: "🥨", description: "Evening bites and pantry treats." },
  { id: "beverages", name: "Beverages", emoji: "🥤", description: "Cold, fresh, and energizing drinks." },
  { id: "essentials", name: "Essentials", emoji: "🧼", description: "Home-care and everyday basics." },
  { id: "bakery", name: "Bakery", emoji: "🍞", description: "Fresh breads, pastries, and baked goods." },
];

const products = [
  {
    id: "prod-avocado",
    slug: "hass-avocado-pack",
    name: "Hass Avocado Pack",
    brand: "GreenHarvest",
    categoryId: "fruit",
    price: 169,
    compareAtPrice: 199,
    rating: 4.8,
    stock: 42,
    eta: "10 mins",
    unit: "2 pcs",
    tags: ["Fresh", "Premium", "Breakfast"],
    description: "Buttery avocados sourced for toast, bowls, and smoothies.",
  },
  {
    id: "prod-spinach",
    slug: "baby-spinach-bag",
    name: "Baby Spinach Bag",
    brand: "Leaf District",
    categoryId: "veg",
    price: 79,
    compareAtPrice: 95,
    rating: 4.6,
    stock: 58,
    eta: "8 mins",
    unit: "250 g",
    tags: ["Leafy", "Salads", "Iron-rich"],
    description: "Tender spinach leaves washed and packed for quick meals.",
  },
  {
    id: "prod-milk",
    slug: "organic-toned-milk",
    name: "Organic Toned Milk",
    brand: "Morning Meadow",
    categoryId: "dairy",
    price: 62,
    rating: 4.7,
    stock: 100,
    eta: "9 mins",
    unit: "1 ltr",
    tags: ["Protein", "Daily", "Organic"],
    description: "Daily-use toned milk from certified farms with cold-chain handling.",
  },
  {
    id: "prod-paneer",
    slug: "fresh-malai-paneer",
    name: "Fresh Malai Paneer",
    brand: "Dairy Craft",
    categoryId: "dairy",
    price: 115,
    compareAtPrice: 129,
    rating: 4.9,
    stock: 36,
    eta: "12 mins",
    unit: "200 g",
    tags: ["High protein", "Fresh", "Dinner"],
    description: "Soft paneer cubes crafted for curries, wraps, and grilled meals.",
  },
  {
    id: "prod-granola",
    slug: "berry-almond-granola",
    name: "Berry Almond Granola",
    brand: "Mornings Co.",
    categoryId: "snacks",
    price: 289,
    rating: 4.5,
    stock: 26,
    eta: "14 mins",
    unit: "400 g",
    tags: ["Healthy", "Breakfast", "Crunchy"],
    description: "Small-batch granola loaded with dried berries and roasted almonds.",
  },
  {
    id: "prod-coldbrew",
    slug: "classic-cold-brew",
    name: "Classic Cold Brew",
    brand: "Roast Lane",
    categoryId: "beverages",
    price: 149,
    rating: 4.4,
    stock: 54,
    eta: "11 mins",
    unit: "300 ml",
    tags: ["Coffee", "Chilled", "Ready to drink"],
    description: "Slow-steeped cold brew with cocoa notes and a smooth finish.",
  },
  {
    id: "prod-oranges",
    slug: "nagpur-oranges-box",
    name: "Nagpur Oranges Box",
    brand: "Citrus Route",
    categoryId: "fruit",
    price: 199,
    compareAtPrice: 239,
    rating: 4.8,
    stock: 62,
    eta: "7 mins",
    unit: "1 kg",
    tags: ["Juicy", "Vitamin C", "Seasonal"],
    description: "Sweet, easy-peel oranges packed for family breakfasts and juicing.",
  },
  {
    id: "prod-detergent",
    slug: "plant-safe-detergent",
    name: "Plant Safe Detergent",
    brand: "HomeKind",
    categoryId: "essentials",
    price: 349,
    rating: 4.3,
    stock: 18,
    eta: "16 mins",
    unit: "2 ltr",
    tags: ["Home care", "Eco", "Refill"],
    description: "Low-residue liquid detergent with a soft botanical fragrance.",
  },
  // Products from GitHub supermarket example
  {
    id: "prod-brown-eggs",
    slug: "brown-eggs",
    name: "Brown Eggs",
    brand: "FarmFresh",
    categoryId: "dairy",
    price: 281,
    rating: 4.0,
    stock: 50,
    eta: "10 mins",
    unit: "12 pcs",
    tags: ["Protein", "Organic", "Breakfast"],
    description: "Raw organic brown eggs in a basket",
  },
  {
    id: "prod-strawberry",
    slug: "sweet-fresh-strawberry",
    name: "Sweet Fresh Strawberry",
    brand: "BerryFarm",
    categoryId: "fruit",
    price: 295,
    rating: 4.0,
    stock: 35,
    eta: "12 mins",
    unit: "500 g",
    tags: ["Sweet", "Fresh", "Seasonal"],
    description: "Sweet fresh strawberry on the wooden table",
  },
  {
    id: "prod-asparagus",
    slug: "asparagus",
    name: "Asparagus",
    brand: "GreenValley",
    categoryId: "veg",
    price: 190,
    rating: 3.0,
    stock: 25,
    eta: "15 mins",
    unit: "400 g",
    tags: ["Fresh", "Healthy", "Vegetable"],
    description: "Asparagus with ham on the wooden table",
  },
  {
    id: "prod-green-smoothie",
    slug: "green-smoothie",
    name: "Green Smoothie",
    brand: "SmoothieCo",
    categoryId: "dairy",
    price: 177,
    rating: 4.0,
    stock: 30,
    eta: "8 mins",
    unit: "350 ml",
    tags: ["Healthy", "Drink", "Fresh"],
    description: "Glass of green smoothie with quail egg's yolk, served with cocktail tube, green apple and baby spinach leaves over tin surface",
  },
  {
    id: "prod-raw-legums",
    slug: "raw-legums",
    name: "Raw Legums",
    brand: "OrganicFarms",
    categoryId: "veg",
    price: 171,
    rating: 2.0,
    stock: 40,
    eta: "14 mins",
    unit: "500 g",
    tags: ["Organic", "Protein", "Legumes"],
    description: "Raw legums on the wooden table",
  },
  {
    id: "prod-baking-cake",
    slug: "baking-cake",
    name: "Baking Cake",
    brand: "SweetBakery",
    categoryId: "bakery",
    price: 111,
    rating: 4.0,
    stock: 20,
    eta: "18 mins",
    unit: "1 kg",
    tags: ["Sweet", "Dessert", "Bakery"],
    description: "Baking cake in rural kitchen - dough recipe ingredients (eggs, flour, sugar) on vintage wooden table from above",
  },
  {
    id: "prod-pesto",
    slug: "pesto-with-basil",
    name: "Pesto with Basil",
    brand: "ItalianKitchen",
    categoryId: "veg",
    price: 182,
    rating: 2.0,
    stock: 28,
    eta: "16 mins",
    unit: "200 g",
    tags: ["Italian", "Sauce", "Fresh"],
    description: "Italian traditional pesto with basil, cheese and oil",
  },
  {
    id: "prod-hazelnut",
    slug: "hazelnut-bowl",
    name: "Hazelnut in Black Ceramic Bowl",
    brand: "NutHarvest",
    categoryId: "veg",
    price: 274,
    rating: 0.0,
    stock: 22,
    eta: "20 mins",
    unit: "300 g",
    tags: ["Nuts", "Healthy", "Snack"],
    description: "Hazelnut in black ceramic bowl on old wooden background. forest wealth. rustic style. selective focus",
  },
  {
    id: "prod-fresh-strawberry-2",
    slug: "fresh-strawberry",
    name: "Fresh Strawberry",
    brand: "BerryFarm",
    categoryId: "fruit",
    price: 286,
    rating: 4.0,
    stock: 45,
    eta: "11 mins",
    unit: "500 g",
    tags: ["Fresh", "Sweet", "Seasonal"],
    description: "Sweet fresh strawberry on the wooden table",
  },
  {
    id: "prod-lemon-salt",
    slug: "lemon-and-salt",
    name: "Lemon and Salt",
    brand: "CitrusGrove",
    categoryId: "fruit",
    price: 158,
    rating: 5.0,
    stock: 38,
    eta: "13 mins",
    unit: "500 g",
    tags: ["Citrus", "Fresh", "Seasoning"],
    description: "Rosemary, lemon and salt on the table",
  },
  {
    id: "prod-homemade-bread",
    slug: "homemade-bread",
    name: "Homemade Bread",
    brand: "ArtisanBakery",
    categoryId: "bakery",
    price: 175,
    rating: 3.0,
    stock: 15,
    eta: "25 mins",
    unit: "500 g",
    tags: ["Fresh", "Bakery", "Artisan"],
    description: "Homemade bread",
  },
  {
    id: "prod-legums-cooked",
    slug: "cooked-legums",
    name: "Cooked Legums",
    brand: "OrganicFarms",
    categoryId: "veg",
    price: 148,
    rating: 0.0,
    stock: 32,
    eta: "12 mins",
    unit: "400 g",
    tags: ["Cooked", "Protein", "Ready"],
    description: "Cooked legums on the wooden table",
  },
];

module.exports = { categories, products };
